<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 7.2.2 (Python 3.13.2 on win32)" generated="2025-03-25T21:54:32.293226" rpa="false" schemaversion="5">
<suite id="s1" name="Login Data" source="C:\Users\User\Documents\p1\tests\login_data.robot">
<test id="s1-t1" name="Case 1" line="16">
<kw name="Open Browser" owner="SeleniumLibrary" type="SETUP">
<msg time="2025-03-25T21:54:32.543496" level="INFO">Opening browser 'chrome' to base url 'https://www.saucedemo.com/' through remote server at 'http://192.168.1.112:4444/wd/hub'.</msg>
<msg time="2025-03-25T21:54:53.581489" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(&lt;urllib3.connection.HTTPConnection object at 0x000002A2D9BDBCB0&gt;, 'Connection to 192.168.1.112 timed out. (connect timeout=None)')': /wd/hub/session</msg>
<msg time="2025-03-25T21:55:14.650246" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(&lt;urllib3.connection.HTTPConnection object at 0x000002A2D9CA5A90&gt;, 'Connection to 192.168.1.112 timed out. (connect timeout=None)')': /wd/hub/session</msg>
<msg time="2025-03-25T21:55:35.692805" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(&lt;urllib3.connection.HTTPConnection object at 0x000002A2D9CA5D10&gt;, 'Connection to 192.168.1.112 timed out. (connect timeout=None)')': /wd/hub/session</msg>
<msg time="2025-03-25T21:55:56.709409" level="INFO">Cannot capture screenshot because no browser is open.</msg>
<msg time="2025-03-25T21:55:56.709810" level="FAIL">MaxRetryError: HTTPConnectionPool(host='192.168.1.112', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by ConnectTimeoutError(&lt;urllib3.connection.HTTPConnection object at 0x000002A2D9CBC8A0&gt;, 'Connection to 192.168.1.112 timed out. (connect timeout=None)'))</msg>
<arg>${url}</arg>
<arg>${browser}</arg>
<arg>remote_url=http://192.168.1.112:4444/wd/hub</arg>
<doc>Opens a new browser instance to the optional ``url``.</doc>
<status status="FAIL" start="2025-03-25T21:54:32.543212" elapsed="84.177686">MaxRetryError: HTTPConnectionPool(host='192.168.1.112', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by ConnectTimeoutError(&lt;urllib3.connection.HTTPConnection object at 0x000002A2D9CBC8A0&gt;, 'Connection to 192.168.1.112 timed out. (connect timeout=None)'))</status>
</kw>
<kw name="Close All Browsers" owner="SeleniumLibrary" type="TEARDOWN">
<doc>Closes all open browsers and resets the browser cache.</doc>
<status status="PASS" start="2025-03-25T21:55:56.721487" elapsed="0.000192"/>
</kw>
<status status="FAIL" start="2025-03-25T21:54:32.541396" elapsed="84.180507">Setup failed:
MaxRetryError: HTTPConnectionPool(host='192.168.1.112', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by ConnectTimeoutError(&lt;urllib3.connection.HTTPConnection object at 0x000002A2D9CBC8A0&gt;, 'Connection to 192.168.1.112 timed out. (connect timeout=None)'))</status>
</test>
<test id="s1-t2" name="Case 2" line="16">
<kw name="Open Browser" owner="SeleniumLibrary" type="SETUP">
<msg time="2025-03-25T21:55:56.724808" level="INFO">Opening browser 'chrome' to base url 'https://www.saucedemo.com/' through remote server at 'http://192.168.1.112:4444/wd/hub'.</msg>
<msg time="2025-03-25T21:56:17.747658" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(&lt;urllib3.connection.HTTPConnection object at 0x000002A2D9CBDCD0&gt;, 'Connection to 192.168.1.112 timed out. (connect timeout=None)')': /wd/hub/session</msg>
<msg time="2025-03-25T21:56:38.790598" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(&lt;urllib3.connection.HTTPConnection object at 0x000002A2D9C660F0&gt;, 'Connection to 192.168.1.112 timed out. (connect timeout=None)')': /wd/hub/session</msg>
<msg time="2025-03-25T21:56:59.833333" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(&lt;urllib3.connection.HTTPConnection object at 0x000002A2D9D9C380&gt;, 'Connection to 192.168.1.112 timed out. (connect timeout=None)')': /wd/hub/session</msg>
<msg time="2025-03-25T21:57:20.867448" level="INFO">Cannot capture screenshot because no browser is open.</msg>
<msg time="2025-03-25T21:57:20.867615" level="FAIL">MaxRetryError: HTTPConnectionPool(host='192.168.1.112', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by ConnectTimeoutError(&lt;urllib3.connection.HTTPConnection object at 0x000002A2D9D9C6B0&gt;, 'Connection to 192.168.1.112 timed out. (connect timeout=None)'))</msg>
<arg>${url}</arg>
<arg>${browser}</arg>
<arg>remote_url=http://192.168.1.112:4444/wd/hub</arg>
<doc>Opens a new browser instance to the optional ``url``.</doc>
<status status="FAIL" start="2025-03-25T21:55:56.724538" elapsed="84.147925">MaxRetryError: HTTPConnectionPool(host='192.168.1.112', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by ConnectTimeoutError(&lt;urllib3.connection.HTTPConnection object at 0x000002A2D9D9C6B0&gt;, 'Connection to 192.168.1.112 timed out. (connect timeout=None)'))</status>
</kw>
<kw name="Close All Browsers" owner="SeleniumLibrary" type="TEARDOWN">
<doc>Closes all open browsers and resets the browser cache.</doc>
<status status="PASS" start="2025-03-25T21:57:20.872963" elapsed="0.000167"/>
</kw>
<status status="FAIL" start="2025-03-25T21:55:56.723486" elapsed="84.149835">Setup failed:
MaxRetryError: HTTPConnectionPool(host='192.168.1.112', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by ConnectTimeoutError(&lt;urllib3.connection.HTTPConnection object at 0x000002A2D9D9C6B0&gt;, 'Connection to 192.168.1.112 timed out. (connect timeout=None)'))</status>
</test>
<test id="s1-t3" name="Case 3" line="16">
<kw name="Open Browser" owner="SeleniumLibrary" type="SETUP">
<msg time="2025-03-25T21:57:20.875767" level="INFO">Opening browser 'chrome' to base url 'https://www.saucedemo.com/' through remote server at 'http://192.168.1.112:4444/wd/hub'.</msg>
<msg time="2025-03-25T21:57:41.915516" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(&lt;urllib3.connection.HTTPConnection object at 0x000002A2D9D9CE20&gt;, 'Connection to 192.168.1.112 timed out. (connect timeout=None)')': /wd/hub/session</msg>
<msg time="2025-03-25T21:58:02.960125" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(&lt;urllib3.connection.HTTPConnection object at 0x000002A2D9D9D370&gt;, 'Connection to 192.168.1.112 timed out. (connect timeout=None)')': /wd/hub/session</msg>
<msg time="2025-03-25T21:58:24.004664" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(&lt;urllib3.connection.HTTPConnection object at 0x000002A2D9D9D590&gt;, 'Connection to 192.168.1.112 timed out. (connect timeout=None)')': /wd/hub/session</msg>
<msg time="2025-03-25T21:58:45.052750" level="INFO">Cannot capture screenshot because no browser is open.</msg>
<msg time="2025-03-25T21:58:45.053000" level="FAIL">MaxRetryError: HTTPConnectionPool(host='192.168.1.112', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by ConnectTimeoutError(&lt;urllib3.connection.HTTPConnection object at 0x000002A2D9D9D7B0&gt;, 'Connection to 192.168.1.112 timed out. (connect timeout=None)'))</msg>
<arg>${url}</arg>
<arg>${browser}</arg>
<arg>remote_url=http://192.168.1.112:4444/wd/hub</arg>
<doc>Opens a new browser instance to the optional ``url``.</doc>
<status status="FAIL" start="2025-03-25T21:57:20.875573" elapsed="84.184092">MaxRetryError: HTTPConnectionPool(host='192.168.1.112', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by ConnectTimeoutError(&lt;urllib3.connection.HTTPConnection object at 0x000002A2D9D9D7B0&gt;, 'Connection to 192.168.1.112 timed out. (connect timeout=None)'))</status>
</kw>
<kw name="Close All Browsers" owner="SeleniumLibrary" type="TEARDOWN">
<doc>Closes all open browsers and resets the browser cache.</doc>
<status status="PASS" start="2025-03-25T21:58:45.060224" elapsed="0.000165"/>
</kw>
<status status="FAIL" start="2025-03-25T21:57:20.874698" elapsed="84.185813">Setup failed:
MaxRetryError: HTTPConnectionPool(host='192.168.1.112', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by ConnectTimeoutError(&lt;urllib3.connection.HTTPConnection object at 0x000002A2D9D9D7B0&gt;, 'Connection to 192.168.1.112 timed out. (connect timeout=None)'))</status>
</test>
<doc>importer la lib selenium</doc>
<status status="FAIL" start="2025-03-25T21:54:32.294584" elapsed="252.766788"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="3" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat name="Login Data" id="s1" pass="0" fail="3" skip="0">Login Data</stat>
</suite>
</statistics>
<errors>
<msg time="2025-03-25T21:54:53.581489" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(&lt;urllib3.connection.HTTPConnection object at 0x000002A2D9BDBCB0&gt;, 'Connection to 192.168.1.112 timed out. (connect timeout=None)')': /wd/hub/session</msg>
<msg time="2025-03-25T21:55:14.650246" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(&lt;urllib3.connection.HTTPConnection object at 0x000002A2D9CA5A90&gt;, 'Connection to 192.168.1.112 timed out. (connect timeout=None)')': /wd/hub/session</msg>
<msg time="2025-03-25T21:55:35.692805" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(&lt;urllib3.connection.HTTPConnection object at 0x000002A2D9CA5D10&gt;, 'Connection to 192.168.1.112 timed out. (connect timeout=None)')': /wd/hub/session</msg>
<msg time="2025-03-25T21:56:17.747658" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(&lt;urllib3.connection.HTTPConnection object at 0x000002A2D9CBDCD0&gt;, 'Connection to 192.168.1.112 timed out. (connect timeout=None)')': /wd/hub/session</msg>
<msg time="2025-03-25T21:56:38.790598" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(&lt;urllib3.connection.HTTPConnection object at 0x000002A2D9C660F0&gt;, 'Connection to 192.168.1.112 timed out. (connect timeout=None)')': /wd/hub/session</msg>
<msg time="2025-03-25T21:56:59.833333" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(&lt;urllib3.connection.HTTPConnection object at 0x000002A2D9D9C380&gt;, 'Connection to 192.168.1.112 timed out. (connect timeout=None)')': /wd/hub/session</msg>
<msg time="2025-03-25T21:57:41.915516" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(&lt;urllib3.connection.HTTPConnection object at 0x000002A2D9D9CE20&gt;, 'Connection to 192.168.1.112 timed out. (connect timeout=None)')': /wd/hub/session</msg>
<msg time="2025-03-25T21:58:02.960125" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(&lt;urllib3.connection.HTTPConnection object at 0x000002A2D9D9D370&gt;, 'Connection to 192.168.1.112 timed out. (connect timeout=None)')': /wd/hub/session</msg>
<msg time="2025-03-25T21:58:24.004664" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(&lt;urllib3.connection.HTTPConnection object at 0x000002A2D9D9D590&gt;, 'Connection to 192.168.1.112 timed out. (connect timeout=None)')': /wd/hub/session</msg>
</errors>
</robot>
